### ISSUE TITLE
Missing regtest variant in BitcoinNetwork type

### ISSUE THREAD

**Issue by adrian-d-hidalgo** [ZenVoich/ic#3]
I am trying to replicate the repo at https://github.com/dfinity/examples/tree/0f0ca7df352a1b7953d80ac8ec19767deea359db/motoko/basic_bitcoin but using mops packages to make things simpler. I noticed that in this line: https://github.com/ZenVoich/ic/blob/e93e2d9931dd0637c49a761c91f7a3b84fa88fd0/src/lib.mo#L3, the regtest variant is missing.

**Comment by ZenVoich** [comment]
Released in 2.0.0
